apiVersion: v1
kind: Service
metadata:
  name: teste-cluster-service
spec:
  type: LoadBalancer
  selector:
    app: teste-cluster
  ports:
    - name: http-web
      port: 80
      targetPort: 3333
      protocol: TCP
